const bcrypt = require('bcryptjs');
const crypto = require('crypto');
const {
  Hospital,
  User,
  Driver,
  WasteBatch,
  DriverRequest,
  PickupRequest,
  Vehicle,
  Notification,
  DisposalFacility,
  Tracking,
} = require('../models');
const googleSheetsService = require('../services/googleSheets.service');

const seedDatabase = async () => {
  try {
    console.log('🌱 [Database] Seeding official BIOWASTE SMART dataset for SIH 2026...');

    // 1. Clear existing in-memory/DB records
    await Hospital.deleteMany({});
    await User.deleteMany({});
    await Driver.deleteMany({});
    await WasteBatch.deleteMany({});
    await DriverRequest.deleteMany({});
    await PickupRequest.deleteMany({});
    await Vehicle.deleteMany({});
    await Notification.deleteMany({});
    await DisposalFacility.deleteMany({});
    await Tracking.deleteMany({});

    // 2. Seed the 12 Verified Telangana Hospitals
    const hospitalsData = [
      {
        hospitalId: 'HOSP-TG-001',
        name: 'Gandhi Hospital',
        type: 'Medical College Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001201',
        contactPerson: 'Dr. M. Raja Rao (Superintendent)',
        address: 'Musheerabad, Secunderabad, Telangana 500003',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500003',
        phone: '+91 40 2750 5566',
        email: 'gandhi@biowastesmart.in',
        latitude: 17.4244,
        longitude: 78.5037,
        bedCapacity: 1200,
        beds: 1200,
        estimatedWaste: '110 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-002',
        name: 'Osmania General Hospital',
        type: 'Medical College Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001202',
        contactPerson: 'Dr. B. Nagender (Superintendent)',
        address: 'Afzal Gunj, High Court Road, Hyderabad, Telangana 500012',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500012',
        phone: '+91 40 2460 0121',
        email: 'osmania@biowastesmart.in',
        latitude: 17.3739,
        longitude: 78.4738,
        bedCapacity: 1168,
        beds: 1168,
        estimatedWaste: '95–130 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-003',
        name: "Nizam's Institute of Medical Sciences (NIMS)",
        type: 'Autonomous Super-Specialty Institute',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001203',
        contactPerson: 'Dr. N. Bheerappa (Director)',
        address: 'Punjagutta Main Road, Somajiguda, Hyderabad, Telangana 500082',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500082',
        phone: '+91 40 2348 9000',
        email: 'nims@biowastesmart.in',
        latitude: 17.4225,
        longitude: 78.4539,
        bedCapacity: 1489,
        beds: 1489,
        estimatedWaste: '120–160 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-004',
        name: 'Niloufer Hospital for Women & Children',
        type: 'Specialty Pediatric Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001204',
        contactPerson: 'Dr. T. Usha Rani (Superintendent)',
        address: 'Red Hills, Lakdikapul, Hyderabad, Telangana 500004',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500004',
        phone: '+91 40 2339 4242',
        email: 'niloufer@biowastesmart.in',
        latitude: 17.3976,
        longitude: 78.4632,
        bedCapacity: 1000,
        beds: 1000,
        estimatedWaste: '70–100 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-005',
        name: 'MNJ Institute of Oncology & Regional Cancer Centre',
        type: 'Specialty Oncology Center',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001205',
        contactPerson: 'Dr. Jayalatha (Director)',
        address: 'Red Hills, Lakdikapul, Hyderabad, Telangana 500004',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500004',
        phone: '+91 40 2331 4455',
        email: 'mnj@biowastesmart.in',
        latitude: 17.3989,
        longitude: 78.4619,
        bedCapacity: 450,
        beds: 450,
        estimatedWaste: '50–75 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-006',
        name: 'Sarojini Devi Eye Hospital',
        type: 'Regional Ophthalmic Institute',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001206',
        contactPerson: 'Dr. V. Rajalingam (Superintendent)',
        address: 'Mehdipatnam, Hyderabad, Telangana 500028',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500028',
        phone: '+91 40 2353 8844',
        email: 'sarojini@biowastesmart.in',
        latitude: 17.3912,
        longitude: 78.4417,
        bedCapacity: 500,
        beds: 500,
        estimatedWaste: '30–45 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-007',
        name: 'Sir Ronald Ross Institute / Government Fever Hospital',
        type: 'Infectious Disease Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001207',
        contactPerson: 'Dr. K. Shankar (Superintendent)',
        address: 'Nallakunta, New Nallakunta, Hyderabad, Telangana 500044',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500044',
        phone: '+91 40 2761 1445',
        email: 'feverhospital@biowastesmart.in',
        latitude: 17.3995,
        longitude: 78.5089,
        bedCapacity: 350,
        beds: 350,
        estimatedWaste: '40–60 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-008',
        name: 'MGM Hospital Warangal',
        type: 'Medical College Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001208',
        contactPerson: 'Dr. V. Chandrasekhar (Superintendent)',
        address: 'MG Road, Ramannapet, Warangal, Telangana 506002',
        district: 'Warangal',
        state: 'Telangana',
        pincode: '506002',
        phone: '+91 870 244 5566',
        email: 'mgmwarangal@biowastesmart.in',
        latitude: 17.9784,
        longitude: 79.5941,
        bedCapacity: 1000,
        beds: 1000,
        estimatedWaste: '80–115 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-009',
        name: 'Apollo Hospitals Jubilee Hills',
        type: 'Multi-Specialty Tertiary Hospital',
        ownership: 'Private',
        registrationNumber: 'TG-MED-001209',
        contactPerson: 'Dr. Ravinder Babu (Medical Director)',
        address: 'Road No 72, Film Nagar, Jubilee Hills, Hyderabad, Telangana 500033',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500033',
        phone: '+91 40 2360 7777',
        email: 'apollojh@biowastesmart.in',
        latitude: 17.4193,
        longitude: 78.4116,
        bedCapacity: 850,
        beds: 850,
        estimatedWaste: '85–120 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-010',
        name: 'KIMS Hospitals Secunderabad',
        type: 'Super-Specialty Tertiary Hospital',
        ownership: 'Private',
        registrationNumber: 'TG-MED-001210',
        contactPerson: 'Dr. B. Bhaskar Rao (Managing Director)',
        address: '1-8-31/1, Minister Road, Krishna Nagar Colony, Secunderabad 500003',
        district: 'Hyderabad',
        state: 'Telangana',
        pincode: '500003',
        phone: '+91 40 4488 5000',
        email: 'kims@biowastesmart.in',
        latitude: 17.4392,
        longitude: 78.4877,
        bedCapacity: 1000,
        beds: 1000,
        estimatedWaste: '90–130 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-011',
        name: 'Government General Hospital Nizamabad',
        type: 'District Teaching Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001211',
        contactPerson: 'Dr. K. Pratima (Superintendent)',
        address: 'Khaleelwadi, Nizamabad, Telangana 503001',
        district: 'Nizamabad',
        state: 'Telangana',
        pincode: '503001',
        phone: '+91 8462 221 144',
        email: 'gghnizamabad@biowastesmart.in',
        latitude: 18.6725,
        longitude: 78.0941,
        bedCapacity: 750,
        beds: 750,
        estimatedWaste: '60–90 kg/day',
        status: 'Active',
      },
      {
        hospitalId: 'HOSP-TG-012',
        name: 'District Headquarters Hospital Karimnagar',
        type: 'District Hospital',
        ownership: 'Government',
        registrationNumber: 'TG-MED-001212',
        contactPerson: 'Dr. CH. Ajay Kumar (Superintendent)',
        address: 'Collectorate Road, Mukarampura, Karimnagar, Telangana 505001',
        district: 'Karimnagar',
        state: 'Telangana',
        pincode: '505001',
        phone: '+91 878 224 3322',
        email: 'dhkarimnagar@biowastesmart.in',
        latitude: 18.4386,
        longitude: 79.1288,
        bedCapacity: 500,
        beds: 500,
        estimatedWaste: '45–70 kg/day',
        status: 'Active',
      },
    ];

    for (const h of hospitalsData) {
      await Hospital.create(h);
      await googleSheetsService.logRow('Hospitals', {
        hospitalId: h.hospitalId,
        name: h.name,
        district: h.district,
        beds: h.beds,
        estimatedWaste: h.estimatedWaste,
        phone: h.phone,
        email: h.email,
        status: h.status,
      });
    }
    console.log('✅ Seeded 12 verified Telangana hospitals with Google Sheets log mirror.');

    // 3. Seed Hospital Admin Users with bcrypt passwords (Format: HospitalName@2026!)
    const hospitalUsers = [
      { name: 'Dr. M. Raja Rao', email: 'gandhi@biowastesmart.in', pass: 'Gandhi@2026!', hospId: 'HOSP-TG-001' },
      { name: 'Dr. B. Nagender', email: 'osmania@biowastesmart.in', pass: 'Osmania@2026!', hospId: 'HOSP-TG-002' },
      { name: 'Dr. N. Bheerappa', email: 'nims@biowastesmart.in', pass: 'NIMS@2026!', hospId: 'HOSP-TG-003' },
      { name: 'Dr. T. Usha Rani', email: 'niloufer@biowastesmart.in', pass: 'Niloufer@2026!', hospId: 'HOSP-TG-004' },
      { name: 'Dr. Jayalatha', email: 'mnj@biowastesmart.in', pass: 'MNJ@2026!', hospId: 'HOSP-TG-005' },
      { name: 'Dr. V. Rajalingam', email: 'sarojini@biowastesmart.in', pass: 'Sarojini@2026!', hospId: 'HOSP-TG-006' },
      { name: 'Dr. K. Shankar', email: 'feverhospital@biowastesmart.in', pass: 'Fever@2026!', hospId: 'HOSP-TG-007' },
      { name: 'Dr. V. Chandrasekhar', email: 'mgmwarangal@biowastesmart.in', pass: 'MGM@2026!', hospId: 'HOSP-TG-008' },
      { name: 'Dr. Ravinder Babu', email: 'apollojh@biowastesmart.in', pass: 'Apollo@2026!', hospId: 'HOSP-TG-009' },
      { name: 'Dr. B. Bhaskar Rao', email: 'kims@biowastesmart.in', pass: 'KIMS@2026!', hospId: 'HOSP-TG-010' },
      { name: 'Dr. K. Pratima', email: 'gghnizamabad@biowastesmart.in', pass: 'Nizamabad@2026!', hospId: 'HOSP-TG-011' },
      { name: 'Dr. CH. Ajay Kumar', email: 'dhkarimnagar@biowastesmart.in', pass: 'Karimnagar@2026!', hospId: 'HOSP-TG-012' },
    ];

    for (const u of hospitalUsers) {
      const passwordHash = bcrypt.hashSync(u.pass, 10);
      await User.create({
        name: u.name,
        email: u.email,
        password: passwordHash,
        role: 'hospital_admin',
        hospitalId: u.hospId,
        designation: 'Medical Superintendent / Waste In-Charge',
        phone: '+91 40 2750 5566',
      });
    }

    // 4. Seed Demo Driver Accounts with bcrypt passwords (Format: PhoneNumber@123 / Ravi@123)
    const driversData = [
      {
        driverId: 'DRV-TS-0101',
        name: 'Ravi Kumar',
        phone: '9876543210',
        email: 'ravi.driver@biowastesmart.in',
        password: '9876543210@123',
        aadhaarNumber: 'XXXX-XXXX-4501',
        aadhaarLast4: '4501',
        drivingLicenseNumber: 'TS-09-2018-9921',
        licenseLast4: '9921',
        vehicleNumber: 'TS-09-UB-4501',
        photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
        status: 'ACTIVE',
      },
      {
        driverId: 'DRV-TS-0102',
        name: 'Kiran Kumar',
        phone: '9848022338',
        email: 'kiran.driver@biowastesmart.in',
        password: '9848022338@123',
        aadhaarNumber: 'XXXX-XXXX-7822',
        aadhaarLast4: '7822',
        drivingLicenseNumber: 'TS-10-2019-3341',
        licenseLast4: '3341',
        vehicleNumber: 'TS-10-EA-3341',
        photoUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
        status: 'ACTIVE',
      },
    ];

    for (const d of driversData) {
      const passwordHash = bcrypt.hashSync(d.password, 10);
      await Driver.create({
        driverId: d.driverId,
        name: d.name,
        phone: d.phone,
        email: d.email,
        passwordHash,
        aadhaarEncrypted: `ENC_AADHAAR_${d.aadhaarLast4}`,
        aadhaarLast4: d.aadhaarLast4,
        licenseNumberEncrypted: `ENC_LIC_${d.licenseLast4}`,
        licenseLast4: d.licenseLast4,
        vehicleNumber: d.vehicleNumber,
        photoUrl: d.photoUrl,
        status: d.status,
      });

      await User.create({
        name: d.name,
        email: d.email,
        phone: d.phone,
        password: passwordHash,
        role: 'driver',
        vehicleNumber: d.vehicleNumber,
        avatar: d.photoUrl,
      });

      await googleSheetsService.logRow('Drivers', {
        driverId: d.driverId,
        name: d.name,
        phone: d.phone,
        email: d.email,
        aadhaarLast4: d.aadhaarLast4,
        licenseLast4: d.licenseLast4,
        vehicleNumber: d.vehicleNumber,
        status: d.status,
      });
    }
    console.log('✅ Seeded Driver accounts with bcrypt hashed passwords.');

    // 5. Seed Dynamic Versioned Waste Batches
    const sampleBatches = [
      {
        batchId: 'BWS-GANDHI-001',
        hospitalId: 'HOSP-TG-001',
        hospitalName: 'Gandhi Hospital',
        category: 'YELLOW',
        wasteCategory: 'YELLOW',
        wasteType: 'Infectious Waste',
        quantityKg: 50.0,
        quantity: 50.0,
        unit: 'kg',
        collectionDate: new Date().toISOString().split('T')[0],
        collectionTime: '08:30',
        date: new Date().toISOString().split('T')[0],
        time: '08:30',
        pickupLocation: 'Gandhi Hospital Gate 3 Bio-Waste Yard',
        contactPerson: 'Dr. M. Raja Rao',
        pickupPhone: '+91 40 2750 5566',
        pickupInstructions: 'Autoclave biohazard double-bagged packaging.',
        qrVersion: 1,
        qrToken: 'tok_gandhi_yellow_sec1001',
        status: 'ACTIVE',
      },
      {
        batchId: 'BWS-OSMANIA-001',
        hospitalId: 'HOSP-TG-002',
        hospitalName: 'Osmania General Hospital',
        category: 'RED',
        wasteCategory: 'RED',
        wasteType: 'Contaminated IV Lines & Dialysis Tubing',
        quantityKg: 35.0,
        quantity: 35.0,
        unit: 'kg',
        collectionDate: new Date().toISOString().split('T')[0],
        collectionTime: '07:50',
        date: new Date().toISOString().split('T')[0],
        time: '07:50',
        pickupLocation: 'Osmania Pathology Bay Gate 1',
        contactPerson: 'Dr. B. Nagender',
        pickupPhone: '+91 40 2460 0121',
        pickupInstructions: 'Deep-freeze preservation compliant bio-containers.',
        qrVersion: 1,
        qrToken: 'tok_osmania_yellow_sec1003',
        status: 'GENERATED',
      },
      {
        batchId: 'BWS-NIMS-2026-0001',
        hospitalId: 'HOSP-TG-003',
        hospitalName: "Nizam's Institute of Medical Sciences (NIMS)",
        category: 'WHITE',
        wasteType: 'Puncture-proof Sharps, Disposable Syringes & Scalpels',
        quantityKg: 14.2,
        quantity: 14.2,
        unit: 'kg',
        collectionDate: new Date().toISOString().split('T')[0],
        collectionTime: '09:10',
        date: new Date().toISOString().split('T')[0],
        time: '09:10',
        pickupLocation: 'NIMS Trauma Center Yard',
        contactPerson: 'Dr. N. Bheerappa',
        pickupPhone: '+91 40 2348 9000',
        pickupInstructions: 'Translucent tamper-proof sealed sharps containers.',
        qrVersion: 1,
        qrToken: 'tok_nims_white_sec1004',
        status: 'GENERATED',
      },
    ];

    for (const b of sampleBatches) {
      b.qrCodeData = JSON.stringify({
        batchId: b.batchId,
        version: b.qrVersion,
        token: b.qrToken,
      });

      await WasteBatch.create(b);
      await googleSheetsService.logRow('WasteBatches', {
        batchId: b.batchId,
        hospitalName: b.hospitalName,
        category: b.category,
        wasteType: b.wasteType,
        quantityKg: b.quantityKg,
        qrVersion: b.qrVersion,
        status: b.status,
      });
    }
    console.log('✅ Seeded dynamic versioned waste batches with secure server tokens.');

    // 6. Seed Clean Initial State for Requests (Empty so driver can test fresh live workflow)
    // Driver requests start fresh for live demonstration

    // 7. Seed Vehicles
    const vehiclesData = [
      {
        vehicleNumber: 'TS-09-UB-4501',
        model: 'Tata Ace EV Bio-Carrier',
        capacityKg: 1000,
        currentLoadKg: 340,
        status: 'Collecting',
        driverName: 'Kiran Kumar',
        driverPhone: '+91 98480 22338',
        currentLatitude: 17.4244,
        currentLongitude: 78.5037,
        speedKmph: 24,
        batteryPercent: 82,
      },
      {
        vehicleNumber: 'TS-10-EA-3341',
        model: 'Mahindra Zor Grand Bio-Transporter',
        capacityKg: 800,
        currentLoadKg: 120,
        status: 'En Route',
        driverName: 'Ramesh Reddy',
        driverPhone: '+91 98765 43210',
        currentLatitude: 17.3739,
        currentLongitude: 78.4738,
        speedKmph: 35,
        batteryPercent: 74,
      },
    ];

    // 8. Seed 10 Authorized Common Bio-Medical Waste Treatment Facilities (CBMWTF)
    const disposalFacilitiesData = [
      {
        facilityId: 'FAC-TG-001',
        facilityName: 'Ramky Enviro CBMWTF (Dundigal Central Facility)',
        email: 'ramky@biowastesmart.in',
        password: 'Ramky@123',
        address: 'Survey No. 64/1, Bahadurpally & Dundigal Road, Gandimaisamma, Hyderabad, Telangana 500043',
        district: 'Medchal-Malkajgiri',
        latitude: 17.5892,
        longitude: 78.4315,
        contactNumber: '+91 40 2319 8800',
        facilityType: 'Common Bio-Medical Waste Treatment Facility (CBMWTF)',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-01-2026',
        qrToken: 'FAC_RAMKY_SECURE_TOKEN_2026_A98',
        qrVersion: 1,
        dailyCapacityKg: 8500,
        activeIncinerators: 3,
        activeAutoclaves: 4,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-002',
        facilityName: 'Maridi Eco Industries CBMWTF Medchal',
        email: 'maridi@biowastesmart.in',
        password: 'Maridi@123',
        address: 'Plot No. 12/A, Industrial Area, Medchal, Hyderabad, Telangana 501401',
        district: 'Medchal',
        latitude: 17.6291,
        longitude: 78.4812,
        contactNumber: '+91 40 2795 3344',
        facilityType: 'Authorized Incineration Facility',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-02-2026',
        qrToken: 'FAC_MARIDI_SECURE_TOKEN_2026_B74',
        qrVersion: 1,
        dailyCapacityKg: 6000,
        activeIncinerators: 2,
        activeAutoclaves: 3,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-003',
        facilityName: 'G.J. Multiclave Bio-Medical Waste Facility Bibinagar',
        email: 'multiclave@biowastesmart.in',
        password: 'Multiclave@123',
        address: 'Sy No. 248, Near AIIMS Campus, Bibinagar, Yadadri Bhuvanagiri, Telangana 508126',
        district: 'Yadadri Bhuvanagiri',
        latitude: 17.4789,
        longitude: 78.7842,
        contactNumber: '+91 40 2988 5511',
        facilityType: 'Authorized Waste Processing Facility',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-03-2026',
        qrToken: 'FAC_GJMULTI_SECURE_TOKEN_2026_C55',
        qrVersion: 1,
        dailyCapacityKg: 7500,
        activeIncinerators: 2,
        activeAutoclaves: 3,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-004',
        facilityName: 'Medicare Environmental Management Pashamylaram',
        email: 'medicare@biowastesmart.in',
        password: 'Medicare@123',
        address: 'Phase III, IDA Pashamylaram, Patancheru, Sangareddy, Telangana 502307',
        district: 'Sangareddy',
        latitude: 17.5218,
        longitude: 78.1895,
        contactNumber: '+91 40 2307 9900',
        facilityType: 'Biomedical Waste Treatment Facility',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-04-2026',
        qrToken: 'FAC_MEDICARE_SECURE_TOKEN_2026_D21',
        qrVersion: 1,
        dailyCapacityKg: 5000,
        activeIncinerators: 2,
        activeAutoclaves: 2,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-005',
        facilityName: 'Clean Enviro Bio-Disposal Cherlapally',
        email: 'cleanenviro@biowastesmart.in',
        password: 'CleanEnviro@123',
        address: 'Plot 88, IDA Cherlapally, Phase II, Hyderabad, Telangana 500051',
        district: 'Medchal-Malkajgiri',
        latitude: 17.4691,
        longitude: 78.6012,
        contactNumber: '+91 40 2712 4433',
        facilityType: 'High-Temperature Incineration Plant',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-05-2026',
        qrToken: 'FAC_CLEAN_SECURE_TOKEN_2026_E11',
        qrVersion: 1,
        dailyCapacityKg: 6500,
        activeIncinerators: 2,
        activeAutoclaves: 3,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-006',
        facilityName: 'Apex Waste Solutions CBMWTF Balanagar',
        email: 'apex@biowastesmart.in',
        password: 'Apex@123',
        address: 'B-14, Industrial Estate, Balanagar, Hyderabad, Telangana 500037',
        district: 'Hyderabad',
        latitude: 17.4725,
        longitude: 78.4389,
        contactNumber: '+91 40 2377 8899',
        facilityType: 'Common Treatment Facility',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-06-2026',
        qrToken: 'FAC_APEX_SECURE_TOKEN_2026_F90',
        qrVersion: 1,
        dailyCapacityKg: 4500,
        activeIncinerators: 1,
        activeAutoclaves: 2,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-007',
        facilityName: 'Telangana Eco-Care Treatment Plant Choutuppal',
        email: 'ecocare@biowastesmart.in',
        password: 'EcoCare@123',
        address: 'NH-65 Highway, Choutuppal, Yadadri Bhuvanagiri, Telangana 508252',
        district: 'Yadadri Bhuvanagiri',
        latitude: 17.2514,
        longitude: 78.8974,
        contactNumber: '+91 40 2866 1122',
        facilityType: 'Regional Bio-Treatment Plant',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-07-2026',
        qrToken: 'FAC_ECOCARE_SECURE_TOKEN_2026_G33',
        qrVersion: 1,
        dailyCapacityKg: 5500,
        activeIncinerators: 2,
        activeAutoclaves: 2,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-008',
        facilityName: 'Warangal Regional Bio-Management Facility',
        email: 'warangalcbmwtf@biowastesmart.in',
        password: 'Warangal@123',
        address: 'Industrial Development Area, Rampur, Warangal, Telangana 506151',
        district: 'Warangal',
        latitude: 17.9512,
        longitude: 79.5412,
        contactNumber: '+91 870 245 8899',
        facilityType: 'Zonal CBMWTF & Incinerator',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-08-2026',
        qrToken: 'FAC_WARANGAL_SECURE_TOKEN_2026_H44',
        qrVersion: 1,
        dailyCapacityKg: 7000,
        activeIncinerators: 2,
        activeAutoclaves: 3,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-009',
        facilityName: 'Karimnagar Green Waste Treatment Plant',
        email: 'karimnagar@biowastesmart.in',
        password: 'Karimnagar@123',
        address: 'Kothapalli Industrial Area, Karimnagar, Telangana 505451',
        district: 'Karimnagar',
        latitude: 18.4389,
        longitude: 79.1287,
        contactNumber: '+91 878 223 4455',
        facilityType: 'Integrated Treatment & Autoclaving Facility',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-09-2026',
        qrToken: 'FAC_KARIMNAGAR_SECURE_TOKEN_2026_I55',
        qrVersion: 1,
        dailyCapacityKg: 4800,
        activeIncinerators: 1,
        activeAutoclaves: 2,
        isActive: true,
      },
      {
        facilityId: 'FAC-TG-010',
        facilityName: 'Nizamabad Bio-Disposal & Incineration Facility',
        email: 'nizamabad@biowastesmart.in',
        password: 'Nizamabad@123',
        address: 'Sarangapur Road, Nizamabad, Telangana 503186',
        district: 'Nizamabad',
        latitude: 18.6612,
        longitude: 78.1124,
        contactNumber: '+91 8462 234 567',
        facilityType: 'District Bio-Waste Disposal Yard',
        cpcbRegistrationNumber: 'CPCB/TSPCB/CBMWTF/TG-10-2026',
        qrToken: 'FAC_NIZAMABAD_SECURE_TOKEN_2026_J66',
        qrVersion: 1,
        dailyCapacityKg: 4200,
        activeIncinerators: 1,
        activeAutoclaves: 2,
        isActive: true,
      },
    ];

    for (const f of disposalFacilitiesData) {
      const passwordHash = bcrypt.hashSync(f.password, 10);
      f.passwordHash = passwordHash;
      f.qrCodeData = JSON.stringify({
        type: 'DISPOSAL_FACILITY',
        facilityId: f.facilityId,
        version: f.qrVersion || 1,
        token: f.qrToken,
      });

      await DisposalFacility.create(f);

      // Create facility User account for portal login
      await User.create({
        name: f.facilityName,
        email: f.email,
        password: passwordHash,
        role: 'facility',
        facilityId: f.facilityId,
      });

      await googleSheetsService.logRow('Disposal_Facilities', {
        facilityId: f.facilityId,
        facilityName: f.facilityName,
        email: f.email,
        address: f.address,
        district: f.district,
        facilityType: f.facilityType,
        cpcbRegistrationNumber: f.cpcbRegistrationNumber,
        status: 'AUTHORIZED_ACTIVE',
      });
    }
    console.log('✅ Seeded 10 authorized CBMWTF treatment & disposal companies with login credentials and dynamic QR tokens.');

    console.log('🌟 [Database] Seed data loaded successfully for Smart India Hackathon!');
  } catch (error) {
    console.error('Database Seed Error:', error);
  }
};

module.exports = seedDatabase;
